#docker-compose file
version: '3.18'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
  employee_management_app:
    container_name: employee_management_app
    image: employee_management_app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongodb
    environment:
      - MONGO_URL=mongodb
